//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON_Jam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON_Jam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label row of internal resource {0} is invalid.{3}    Expected value = {1}{3}    Actual value   = {2}.
        /// </summary>
        internal static string ERRMSG_CORRUPTED_EMBBEDDED_RESOURCE_LABEL {
            get {
                return ResourceManager.GetString("ERRMSG_CORRUPTED_EMBBEDDED_RESOURCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail record {0} of internal resource {1} is invalid.{5}    Expected field count = {2}{5}    Actual field count   = {3}{5}    Actual record        = {4}.
        /// </summary>
        internal static string ERRMSG_CORRUPTED_EMBEDDED_RESOURCE_DETAIL {
            get {
                return ResourceManager.GetString("ERRMSG_CORRUPTED_EMBEDDED_RESOURCE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Report File:   .
        /// </summary>
        internal static string FILE_LABEL_CONTENT_REPORT {
            get {
                return ResourceManager.GetString("FILE_LABEL_CONTENT_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File:            .
        /// </summary>
        internal static string FILE_LABEL_FINAL {
            get {
                return ResourceManager.GetString("FILE_LABEL_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File:             .
        /// </summary>
        internal static string FILE_LABEL_INPUT {
            get {
                return ResourceManager.GetString("FILE_LABEL_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate File:      .
        /// </summary>
        internal static string FILE_LABEL_INTERMEDIATE {
            get {
                return ResourceManager.GetString("FILE_LABEL_INTERMEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press Return to fully stop the program..
        /// </summary>
        internal static string MSG_AWAIT_CARBON_UNIT {
            get {
                return ResourceManager.GetString("MSG_AWAIT_CARBON_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item\tActivity_Date\tOpen\tHigh\tLow\tClose\tAdjustedClose\tVolume\tDividendAmount\tSplitCoefficient.
        /// </summary>
        internal static string MSG_RESPONSE_DETAILS_LABELS {
            get {
                return ResourceManager.GetString("MSG_RESPONSE_DETAILS_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata from response: Information   = {0}{6}                             Symbol        = {1}{6}                             LastRefreshed = {2}{6}                             OutputSize    = {3}{6}                             TimeZone      = {4}{6}                             Detail Count  = {5}{6}.
        /// </summary>
        internal static string MSG_RESPONSE_METADATA {
            get {
                return ResourceManager.GetString("MSG_RESPONSE_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.{2},{5}{3} ({4} UTC){5}.
        /// </summary>
        internal static string MSG_START {
            get {
                return ResourceManager.GetString("MSG_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}{0} Done, {1} ({2} UTC){4}Running time = {3}.
        /// </summary>
        internal static string MSG_STOP {
            get {
                return ResourceManager.GetString("MSG_STOP", resourceCulture);
            }
        }
    }
}
